
services:
  app:
    image: panel-api-server:latest
    container_name: api-server
    restart: always
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./channels:/app/channels
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mails:/app/mails
      - ./static:/app/staticstatic
      - ./tasks:/app/tasks
      - ./uploadfiles:/app/uploadfiles
      - ./views:/app/views
    ports:
      - ${SERVER_PORT:-4000}:4000

  redis:
    image: redis:6.2-alpine
    container_name: api-server_redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: redis-server --requirepass ${REDIS_PASS}